Update pip_installation.rst
Changed to double quotes on Windows Anaconda install, :
pip install 'isaacsim[all,extscache]==4.5.0' --extra-index-url https://pypi.nvidia.com

Was erroring with :
ERROR: Invalid requirement: "'isaacsim[all,extscache]==4.5.0'": Expected package name at the start of dependency specifier
    'isaacsim[all,extscache]==4.5.0'
    ^


Signed-off-by: Jason Schugardt <142111787+jschugardt@users.noreply.github.com>